### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [nunorc/nunorc.zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by nunorc** [comment]
Thank you for reporting this, license added. Please note that this is a theme not a plugin.

Thank you

**Comment by unixorn** [comment]
The repo was named before I broke it into separate plugin and theme sections :-)
